export const content = {
    en: {
        navHome: 'Home',
        navFeatures: 'Features',
        navContact: 'Contact',
        langButton: 'हिन्दी',
        heroTitle: 'Empowering Farmers with Modern Technology',
        heroSubtitle: 'Real-time weather updates, crop advice, and market prices, all in one place.',
        heroCta: 'Get Started Now',
        featuresTitle: 'Our Key Features',
        feature1Title: 'Weather Forecast',
        feature1Desc: 'Accurate weather predictions to help you plan your farming activities.',
        feature2Title: 'Market Prices',
        feature2Desc: 'Live mandi rates for your crops to ensure you get the best price.',
        feature3Title: 'Crop Advisory',
        feature3Desc: 'Expert guidance on crop management from sowing to harvesting.',
        feature4Title: 'Farmer Community',
        feature4Desc: 'Connect with fellow farmers and agricultural experts to share knowledge.',
        testimonialsTitle: 'What Our Farmers Say',
        testimonial1Text: 'KisanMitra has transformed the way I farm. The real-time market prices are a game-changer!',
        testimonial1Name: 'Ram Singh, Haryana',
        testimonial2Text: 'The crop advisory feature saved my harvest this season. Incredibly helpful and easy to use.',
        testimonial2Name: 'Priya Patil, Maharashtra',
        ctaTitle: 'Ready to Grow with Us?',
        ctaSubtitle: 'Join thousands of farmers who are making smarter decisions with KisanMitra.',
        ctaButton: 'Sign Up for Free',
        footerText: '© 2025 KisanMitra. All Rights Reserved.',
    },
    hi: {
        navHome: 'होम',
        navFeatures: 'विशेषताएँ',
        navContact: 'संपर्क',
        langButton: 'English',
        heroTitle: 'आधुनिक तकनीक से किसानों को सशक्त बनाना',
        heroSubtitle: 'मौसम की जानकारी, फसल सलाह और बाजार भाव, सब कुछ एक ही स्थान पर।',
        heroCta: 'अभी शुरू करें',
        featuresTitle: 'हमारी मुख्य विशेषताएँ',
        feature1Title: 'मौसम पूर्वानुमान',
        feature1Desc: 'आपकी खेती की गतिविधियों की योजना बनाने में मदद करने के लिए सटीक मौसम की भविष्यवाणी।',
        feature2Title: 'मंडी भाव',
        feature2Desc: 'आपकी फसलों के लिए लाइव मंडी दरें ताकि आपको सर्वोत्तम मूल्य मिल सके।',
        feature3Title: 'फसल सलाह',
        feature3Desc: 'बुवाई से लेकर कटाई तक फसल प्रबंधन पर विशेषज्ञ मार्गदर्शन।',
        feature4Title: 'किसान समुदाय',
        feature4Desc: 'ज्ञान साझा करने के लिए साथी किसानों और कृषि विशेषज्ञों से जुड़ें।',
        testimonialsTitle: 'हमारे किसान क्या कहते हैं',
        testimonial1Text: 'किसानमित्र ने मेरी खेती करने का तरीका बदल दिया है। वास्तविक समय में बाजार मूल्य मिलना एक गेम-चेंजर है!',
        testimonial1Name: 'राम सिंह, हरियाणा',
        testimonial2Text: 'फसल सलाह सुविधा ने इस मौसम में मेरी फसल बचाई। अविश्वसनीय रूप से सहायक और उपयोग में आसान।',
        testimonial2Name: 'प्रिया पाटिल, महाराष्ट्र',
        ctaTitle: 'हमारे साथ बढ़ने के लिए तैयार हैं?',
        ctaSubtitle: 'उन हजारों किसानों से जुड़ें जो किसानमित्र के साथ बेहतर निर्णय ले रहे हैं।',
        ctaButton: 'मुफ्त में साइन अप करें',
        footerText: '© 2025 किसानमित्र। सर्वाधिकार सुरक्षित।',
    },
};